# Generated by Django 3.1.3 on 2021-05-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210525_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.tipo_producto'),
            preserve_default=False,
        ),
    ]
