# Generated by Django 3.1.3 on 2021-05-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210525_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
